# Generated by Django 5.1.1 on 2024-12-11 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SafeHer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hazardreport',
            old_name='street_name',
            new_name='location_name',
        ),
    ]
