# Generated by Django 5.1.1 on 2024-12-11 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SafeHer', '0002_rename_street_name_hazardreport_location_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hazardreport',
            old_name='location_name',
            new_name='street_name',
        ),
    ]
