# Generated by Django 4.2.16 on 2024-12-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafeHer', '0005_profile_emergency_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='emergency_contact',
            new_name='emergency_contact_name_1',
        ),
        migrations.AddField(
            model_name='profile',
            name='emergency_contact_name_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='emergency_contact_name_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='emergency_contact_phone_1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='emergency_contact_phone_2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='emergency_contact_phone_3',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='emergency_contact_priority_1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='emergency_contact_priority_2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='emergency_contact_priority_3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
