# Generated by Django 5.1.2 on 2024-12-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafeHer', '0006_rename_emergency_contact_profile_emergency_contact_name_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedHazardArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
